// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMagnets(arg1, arg2) {
  return window['go']['main']['App']['GetMagnets'](arg1, arg2);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}
